services:
  backend:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    ports:
      - "25000:25000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./ex2
      dockerfile: Dockerfile
    ports:
      - "25001:25001"
    depends_on:
      - backend

  # MongoDB base
  mongodb:
    image: mongo:latest
    # depends_on:
    #   - mongo-seed

  # Importa a coleção "edicoes"
  mongo-seed-edicoes:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./dataset.json:/dataset.json
    command: mongoimport --host mongodb --db eurovisao --collection edicoes --file /dataset.json --jsonArray

  # Importa a coleção "musicas"
  mongo-seed-musicas:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./musicas.json:/musicas.json
    command: mongoimport --host mongodb --db eurovisao --collection musicas --file /musicas.json --jsonArray
